:bug: Fixes #206 Wrong calculation of left and right position of tooltip
SimformSolutionsPvtLtd/flutter_showcaseview pull request #264
Opened 2022-08-20 21:51 UTC by vatsaltanna

2022-08-22 13:51 UTC, DhavalRKansara approved these changes

2022-09-09 10:20 UTC, DevarshRanpara requested changes

2022-09-09 10:20 UTC, DevarshRanpara commented on lib/src/tooltip_widget.dart
> +      tooltipWidth = widget.screenSize!.width - 20;
Can we use constant for 20?

2022-09-09 10:20 UTC, DevarshRanpara commented on lib/src/tooltip_widget.dart
> +      tooltipWidth = maxTextWidth + 15;
Can we use constant for 15?

2022-09-09 10:20 UTC, DevarshRanpara commented on lib/src/tooltip_widget.dart
> +      var leftPositionValue =
Can we use `double` here instead of `var`?

2022-09-09 10:20 UTC, DevarshRanpara commented on lib/src/tooltip_widget.dart
> +      return (leftPositionValue + tooltipWidth) >
Can we remove ternary operators and use conditions to increase readability?

2022-09-09 10:20 UTC, DevarshRanpara commented on lib/src/tooltip_widget.dart
> +    if (widget.position != null) {
Can we remove ternary operators and use conditions to increase readability?

2022-09-23 10:04 UTC, DevarshRanpara approved these changes

2022-09-23 10:12 UTC, merged