chore: workflow for PR title validation
SimformSolutionsPvtLtd/flutter_showcaseview pull request #286
Opened 2022-10-21 08:43 UTC by ShwetaChauhan18

- workflow for PR title validation

2022-12-29 09:06 UTC, ujas-m-simformsolutions requested changes

2022-12-29 09:06 UTC, ujas-m-simformsolutions commented on .github/workflows/title-validation.yml
> +      - synchronize
Also add this type `reopened`.

2022-12-29 09:06 UTC, ujas-m-simformsolutions commented on CHANGELOG.md
> +- PR title validation workflow added
Add `added` in front.

2022-12-30 08:21 UTC, ujas-m-simformsolutions approved these changes
LGTM

2022-12-30 08:24 UTC, vatsaltanna-simformsolutions commented on CHANGELOG.md
> +## [2.0.0+2] - December 30, 2022 (Unreleased)
please change the version to 2.0.1

2022-12-30 08:27 UTC, merged