feat: :sparkles: Add feasibility to add `textDirection` of `title` and `description`.
SimformSolutionsPvtLtd/flutter_showcaseview pull request #356
Opened 2023-03-15 10:07 UTC by dhvanit-v-simformsolutions

:sparkles: (https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/issues/148) Add feasibility to add `textDirection` of `title` and `description`.

# Description

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

[Contributor Guide]: https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/blob/master/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

2023-03-15 11:42 UTC, ujas-m-simformsolutions requested changes

2023-03-15 11:42 UTC, ujas-m-simformsolutions commented on lib/src/showcase.dart
> +    this.titleTextDirection,
Text direction will only be used in tool-tip not in custom widget so don't pass it in constructor. Make it null after constructor initialization.

2023-03-15 11:42 UTC, ujas-m-simformsolutions commented on lib/src/showcase.dart
> +    this.descriptionTextDirection,
^^

2023-03-15 11:42 UTC, ujas-m-simformsolutions commented on CHANGELOG.md
> +## (Unreleased)
Add version number and do update pubspec and readme

2023-03-15 12:11 UTC, ujas-m-simformsolutions approved these changes
![lgtm](https://user-images.githubusercontent.com/76939001/225305409-fc27c13b-9363-477c-9ead-ac9a2628be2e.jpg)

2023-03-22 08:22 UTC, vatsaltanna-simformsolutions commented on README.md
> +| descriptionPadding           | TextDirection?      |                                   | Give textDirection to description
descriptionPadding -> descriptionTextDirection

2023-03-22 09:16 UTC, merged