fix: 🐛 Fixed ToolTip Slide Transition
SimformSolutionsPvtLtd/flutter_showcaseview pull request #369
Opened 2023-04-06 06:39 UTC by faiyaz-shaikh

# Description
Fixed ToolTip Slide Transition

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

[Contributor Guide]: https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/blob/master/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

2023-04-07 06:08 UTC, ujas-m-simformsolutions requested changes

2023-04-07 06:08 UTC, ujas-m-simformsolutions commented on lib/src/tooltip_widget.dart
> +class ToolTipSlideTransition extends AnimatedWidget {
This file is getting very big now, can you please saparate code in multiple files.

2023-04-12 06:00 UTC, ujas-m-simformsolutions requested changes

2023-04-12 06:00 UTC, ujas-m-simformsolutions commented on lib/src/tooltip_widget.dart
> +                    0.0, widget.movingEndDistance * contentOffsetMultiplier),
Add comma

2023-04-12 06:00 UTC, ujas-m-simformsolutions commented on lib/src/tooltip_widget.dart
> +                        EdgeInsets.only(top: paddingTop, bottom: paddingBottom),
^^

2023-04-13 07:33 UTC, faiyaz-shaikh commented on lib/src/tooltip_widget.dart
> +                    0.0, widget.movingEndDistance * contentOffsetMultiplier),
Done

2024-03-08 11:41 UTC, Sahil-Simform requested changes

2024-03-08 11:41 UTC, Sahil-Simform commented on lib/src/tooltip_widget.dart
> +                    0.0, widget.movingEndDistance * contentOffsetMultiplier),
Please reformat this for better readability

2024-03-08 16:00 UTC, aditya-css requested changes

2024-04-18 09:18 UTC, Ujas-Majithiya approved these changes
![lgtm](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/56400956/24a5adb5-5adf-450b-ac8c-63d4c531a871)

2024-04-18 09:19 UTC, Sahil-Simform approved these changes
LGTM!

2024-04-18 09:20 UTC, ujas-m-simformsolutions approved these changes
LGTM

2024-04-18 09:29 UTC, merged