fix: :zap: Optimize `GetPosition` class
SimformSolutionsPvtLtd/flutter_showcaseview pull request #370
Opened 2023-04-06 14:07 UTC by ujas-m-simformsolutions

# Description

Reduced call for render object. Improved conditions.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

None.

[Contributor Guide]: https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/blob/master/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

2024-03-06 05:52 UTC, aditya-css requested changes

2024-03-06 05:52 UTC, aditya-css commented on lib/src/get_position.dart
> +        (_boxOffset?.dx.isNaN ?? true) ||
Please create an extension for this.

2024-03-06 05:52 UTC, aditya-css commented on lib/src/get_position.dart
> +      return 0 - padding.top;
I believe you can skip subtracting from 0 and directly assign negative sign here.

2024-03-06 08:53 UTC, aditya-css approved these changes

2024-03-06 08:54 UTC, merged

2024-03-27 15:30 UTC, guenth39 commented
When will this be released? I need the fix and therefore have to use master right now, it would be nice to be able to switch back to the pub version.

2024-04-19 09:27 UTC, aditya-css commented
Hey @guenth39, We would like to inform that we have released this commit with 2.1.0 version of this package.