feat: ✨ Add disableAutoScroll to Showcase
SimformSolutionsPvtLtd/flutter_showcaseview pull request #386
Opened 2023-08-14 08:38 UTC by Sensirex

# Description
Add disabling auto scroll (disableAutoScroll) for concrete tooltip (Showcase)

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

[Contributor Guide]: https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/blob/master/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

2024-03-08 11:07 UTC, Sahil-Simform requested changes

2024-03-08 11:09 UTC, Sahil-Simform commented
Hi @Sensirex, thank you for your contribution. Can you please resolve conflicts and PR comments?

2024-12-03 11:02 UTC, Sahil-Simform approved these changes

2024-12-03 11:18 UTC, aditya-css approved these changes

2024-12-03 11:18 UTC, merged