feat: ✨Add staticContainer into ToolTipWidget for a custom tooltip th…
SimformSolutionsPvtLtd/flutter_showcaseview pull request #396
Opened 2023-09-21 10:23 UTC by MichaelCadavillo

…at can be placed anywhere on screen and is not affected by the animation.

# Description
Implemented a static version of the custom tooltip widget `container` field. Primarily used for when we want to show another widget (perhaps a 'Skip Showcases' button) which is not affected by the animation that is given to the `container` field.

## Checklist
- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?
- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues
Closes #395

2024-04-26 08:48 UTC, erperejildo approved these changes

2024-04-26 08:49 UTC, erperejildo commented
I need to integrate a skip button and I don't want to rely on custom buttons for now if this is going to be implemented. This was opened 7 months ago. Any plan to merge this soon?

2024-05-01 14:48 UTC, mgaucher approved these changes

2024-05-15 14:58 UTC, erperejildo commented
@aditya-css any update?

2024-06-04 13:50 UTC, mgaucher commented
Is it possible to add it for the Showcase() constructor too ? (when container is null)

2024-10-17 01:55 UTC, omi-jeybsbaterna commented
any update on this PR?

2024-12-03 05:29 UTC, aditya-css requested changes
Please also consider providing an option to disable the global floating action widget for particular showcase.

2024-12-03 05:29 UTC, aditya-css commented on README.md
Please update for globalFloatingActionWidget as well.

2024-12-03 05:29 UTC, aditya-css commented on example/lib/main.dart
> +                            ),
Please keep this minimal.

2024-12-03 05:29 UTC, aditya-css commented on lib/src/widget/floating_action_widget.dart
> +    double? right;
Please have default values.

2024-12-03 08:04 UTC, aditya-css requested changes

2024-12-03 08:04 UTC, aditya-css commented on lib/src/showcase_widget.dart
> +  final List<GlobalKey> hideFloatingActionWidgetForShowcase;
This should rather be a function as to make it more dynamic.

2024-12-03 08:04 UTC, aditya-css commented on lib/src/showcase_widget.dart
> +      widget.hideFloatingActionWidgetForShowcase.contains(ids![activeWidgetId!])
Please avoid force null checks.

2024-12-03 08:04 UTC, aditya-css commented on lib/src/tooltip_widget.dart
> +      if (widget.floatingActionWidget != null) {
Please prefer positive condition.

2024-12-03 08:04 UTC, aditya-css commented on lib/src/showcase_widget.dart
> +  FloatingActionWidget Function(BuildContext)? get globalFloatingActionWidget =>
Please use typedef.

2024-12-03 12:17 UTC, JanakMistry2000 requested changes

2024-12-04 04:22 UTC, aditya-css requested changes

2024-12-04 04:22 UTC, aditya-css commented on lib/src/showcase_widget.dart
> +    for (var item in widget.hideFloatingActionWidgetForShowcase) item: true
Please make this final.

2024-12-04 04:22 UTC, aditya-css commented on lib/src/showcase_widget.dart
> +  List<GlobalKey> get hideFloatingActionWidgetForShowcase =>
Please rename this as to make it differ from the function.

2024-12-04 04:22 UTC, aditya-css commented on lib/src/showcase_widget.dart
> +    _hideFloatingWidgetKeys = {for (var item in updatedList) item: true};
Please make this final.

2024-12-05 09:13 UTC, JanakMistry2000 approved these changes

2024-12-26 13:56 UTC, nanox77 commented
Any update? Changes is already approved 😄

2024-12-31 05:19 UTC, aditya-css approved these changes

2024-12-31 05:22 UTC, merged