Fix Text Style on Flutter 3.22
SimformSolutionsPvtLtd/flutter_showcaseview pull request #433
Opened 2024-05-14 02:00 UTC by chandrabezzo

# Description

After Flutter SDK 3.22, removed deprecated text theme for headline6 and subtitle2. So, we need to fix this issue.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

[Flutter Release Notes 3.22]: https://docs.flutter.dev/release/release-notes/release-notes-3.22.0

2024-05-14 09:21 UTC, gmWheeler001 approved these changes

2024-05-14 11:39 UTC, VB10 commented
lgtm 🌸

2024-05-14 11:48 UTC, VB10 approved these changes

2024-05-16 12:59 UTC, ashu3699 approved these changes

2024-05-16 13:00 UTC, ashu3699 requested changes
please add this..

2024-05-16 13:01 UTC, ashu3699 approved these changes

2024-05-17 03:39 UTC, JoseDRojasA approved these changes

2024-05-23 17:21 UTC, ziqq approved these changes

2024-05-30 14:53 UTC, aditya-css commented
Hello @chandrabezzo, Thank you for raising this PR. Can you please bump the version to 3.0.0 pubspec and changelog?

2024-05-30 17:32 UTC, aditya-css requested changes

2024-05-30 17:32 UTC, aditya-css commented on pubspec.yaml
> +version: 2.1.2
Please update this to 3.0.0.

2024-05-31 02:06 UTC, chandrabezzo commented
Done @aditya-css

2024-05-31 03:38 UTC, aditya-css approved these changes

2024-05-31 03:51 UTC, merged

2024-05-31 10:08 UTC, Obada2020 commented
how to pull this in my git

2024-05-31 15:08 UTC, victor337 commented
> how to pull this in my git

I think he will update in pub.dev, but in the meantime use this:

```
showcaseview:
    git:
      url: https://github.com/chandrabezzo/flutter_showcaseview
      ref: ae8d8a327cdede529d264d1df02892fdc6161688
```