fix!: 🐛 Fixed TitleAlign Issue
SimformSolutionsPvtLtd/flutter_showcaseview pull request #459
Opened 2024-07-02 11:23 UTC by rashi-simform

# Description
- Added `titleAlignment` and `descriptionAlignment` parameters to align title and description within the tooltip widget
- Renamed parameters `titleAlignment` to `titleTextAlign` and `descriptionAlignment` to `descriptionTextAlign`

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [x] Yes, this PR is a breaking change.
- [ ] No, this PR is not a breaking change.

## Related Issues
Closes #457 

[Contributor Guide]: https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/blob/master/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

2024-07-05 06:43 UTC, aditya-chavda requested changes

2024-07-05 06:43 UTC, aditya-chavda commented on README.md
> +Renamed parameters `titleAlignment` to `titleTextAlign` and `descriptionAlignment` to `descriptionTextAlign` to correspond it more with the TextAlign property
Please also mention that the existing variables' behaviour/purpose has been changed.

2024-07-05 06:43 UTC, aditya-chavda commented on lib/src/showcase.dart
> +  /// Title alignment within tooltip widget
Can you please add widget word in there?
```suggestion
  /// Title widget alignment within tooltip widget
```

2024-07-05 06:43 UTC, aditya-chavda commented on lib/src/tooltip_widget.dart
>                                      : CrossAxisAlignment.center,
Please see if this is still required after the usage of `Align` as parent of the children.

2024-07-05 06:43 UTC, aditya-chavda commented on lib/src/tooltip_widget.dart
> +    required this.titleTextAlign,
Can you please put this with the other text align and alignment property below?

2024-11-21 13:52 UTC, Sahil-Simform approved these changes
LGTM!

2024-12-02 11:43 UTC, aditya-css approved these changes

2024-12-02 11:43 UTC, merged